version: '2'
services:

    redis-auth:
      image: redis
      ports:
        - 8081:6379
      networks:
            - default_network_name

    authentication-service:
      image: authentication-service-docker
      ports:
        - 8080:8080
      networks:
            - default_network_name

networks:
    default_network_name:
        driver: bridge